language: objective-c
cache: cocoapods
podfile: Project/Podfile
before_install:
  - pod install --project-directory=Project
script:
- set -o pipefail && xcodebuild test -workspace Project/CocoaPods-ObjC.xcworkspace -scheme Demo ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
