platform :osx, '10.8'
inhibit_all_warnings!

target 'Demo' do
  pod 'CocoaPods-ObjC', :path => '../'
  pod 'TransformerKit'
  pod 'KGNoise'

  pod 'NSString+Ruby'
  pod 'REKit'
  pod 'ObjectiveSugar'
end

target 'DemoTests' do
  pod 'Expecta'
  pod 'Specta'
  pod 'OCMockito'
end

#target 'executable', :exclusive => true do
#  pod 'DSUnixTask/XPCService'
#end
